namespace Apogee
{
    //------------------------------------------------------------------------------
    // <auto-generated>
    //     This code was generated by a tool.
    //     Runtime Version:4.0.30319.42000
    //
    //     Changes to this file may cause incorrect behavior and will be lost if
    //     the code is regenerated.
    // </auto-generated>
    //------------------------------------------------------------------------------

    using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.agfa.com/apoxml")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.agfa.com/apoxml", IsNullable=false)]
public partial class ApoXML : ApoXmlCsLib.ApoXmlBase<Apogee.ApoXML>
    {
    
    private GeneralIDType[] generalIDsField;
    
    private BaseContactType customerContactField;
    
    private BaseContactType[] senderContactField;
    
    private BaseContactType[] approverContactField;
    
    private MultiContactType[] multiContactField;
    
    private BaseContactType administratorContactField;
    
    private CSRType cSRField;
    
    private BindingType bindingField;
    
    private ColorType colorField;
    
    private PaperStockType paperStockField;
    
    private JMFType jMFField;
    
    private PartCoverType partCoverField;
    
    private BasePartType partSingleField;
    
    private BasePartType[] partField;
    
    private string amountField;
    
    private string customerOrderIDField;
    
    private PrintProcessType printProcessField;
    
    private string productTypeField;
    
    private PublishLevelType publishLevelField;
    
    private bool publishLevelFieldSpecified;
    
    private string uRLField;
    
    private string commentsField;
    
    private string commentURLField;
    
    private string descriptionField;
    
    private string endDateField;
    
    private string jobNameField;
    
    private string operatorField;
    
    private string orderNumberField;
    
    private string priorityField;
    
    private string asantiQualityField;
    
    private string asantiImagePresetField;
    
    private string asantiPinSetField;
    
    private string asantiPinConfigField;
    
    private string asantiCPMField;
    
    private AsantiWhiteGenerationType asantiWhiteGenerationField;
    
    private bool asantiWhiteGenerationFieldSpecified;
    
    private AsantiWhiteOrderType asantiWhiteOrderField;
    
    private bool asantiWhiteOrderFieldSpecified;
    
    private string productField;
    
    private PrintQualityType printQualityField;
    
    private bool printQualityFieldSpecified;
    
    private string namedFeaturesField;
    
    private bool noImposeField;
    
    private bool noImposeFieldSpecified;
    
    private string ticketTemplateField;
    
    private string versionsField;
    
    private string versionLayersField;
    
    private string agentNameField;
    
    private string agentNameJDFField;
    
    private string agentVersionField;
    
    private string agentVersionJDFField;
    
    private ApoXMLDecimalSeparator decimalSeparatorField;
    
    private ApoXMLThousandSeparator thousandSeparatorField;
    
    private ApoXMLUnit unitField;
    
    public ApoXML() {
        this.printProcessField = PrintProcessType.ConventionalPrinting;
        this.versionsField = "";
        this.versionLayersField = "";
        this.thousandSeparatorField = ApoXMLThousandSeparator.Item;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlArrayItemAttribute("GeneralID", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
    public GeneralIDType[] GeneralIDs {
        get {
            return this.generalIDsField;
        }
        set {
            this.generalIDsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public BaseContactType CustomerContact {
        get {
            return this.customerContactField;
        }
        set {
            this.customerContactField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("SenderContact", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public BaseContactType[] SenderContact {
        get {
            return this.senderContactField;
        }
        set {
            this.senderContactField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ApproverContact", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public BaseContactType[] ApproverContact {
        get {
            return this.approverContactField;
        }
        set {
            this.approverContactField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("MultiContact", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public MultiContactType[] MultiContact {
        get {
            return this.multiContactField;
        }
        set {
            this.multiContactField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public BaseContactType AdministratorContact {
        get {
            return this.administratorContactField;
        }
        set {
            this.administratorContactField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public CSRType CSR {
        get {
            return this.cSRField;
        }
        set {
            this.cSRField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public BindingType Binding {
        get {
            return this.bindingField;
        }
        set {
            this.bindingField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public ColorType Color {
        get {
            return this.colorField;
        }
        set {
            this.colorField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public PaperStockType PaperStock {
        get {
            return this.paperStockField;
        }
        set {
            this.paperStockField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public JMFType JMF {
        get {
            return this.jMFField;
        }
        set {
            this.jMFField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public PartCoverType PartCover {
        get {
            return this.partCoverField;
        }
        set {
            this.partCoverField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public BasePartType PartSingle {
        get {
            return this.partSingleField;
        }
        set {
            this.partSingleField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Part", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public BasePartType[] Part {
        get {
            return this.partField;
        }
        set {
            this.partField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string Amount {
        get {
            return this.amountField;
        }
        set {
            this.amountField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string CustomerOrderID {
        get {
            return this.customerOrderIDField;
        }
        set {
            this.customerOrderIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    //[System.ComponentModel.DefaultValueAttribute(PrintProcessType.ConventionalPrinting)]
    public PrintProcessType PrintProcess {
        get {
            return this.printProcessField;
        }
        set {
            this.printProcessField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ProductType {
        get {
            return this.productTypeField;
        }
        set {
            this.productTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public PublishLevelType PublishLevel {
        get {
            return this.publishLevelField;
        }
        set {
            this.publishLevelField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool PublishLevelSpecified {
        get {
            return this.publishLevelFieldSpecified;
        }
        set {
            this.publishLevelFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
    public string URL {
        get {
            return this.uRLField;
        }
        set {
            this.uRLField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Comments {
        get {
            return this.commentsField;
        }
        set {
            this.commentsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string CommentURL {
        get {
            return this.commentURLField;
        }
        set {
            this.commentURLField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Description {
        get {
            return this.descriptionField;
        }
        set {
            this.descriptionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string EndDate {
        get {
            return this.endDateField;
        }
        set {
            this.endDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string JobName {
        get {
            return this.jobNameField;
        }
        set {
            this.jobNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Operator {
        get {
            return this.operatorField;
        }
        set {
            this.operatorField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string OrderNumber {
        get {
            return this.orderNumberField;
        }
        set {
            this.orderNumberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string Priority {
        get {
            return this.priorityField;
        }
        set {
            this.priorityField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string AsantiQuality {
        get {
            return this.asantiQualityField;
        }
        set {
            this.asantiQualityField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string AsantiImagePreset {
        get {
            return this.asantiImagePresetField;
        }
        set {
            this.asantiImagePresetField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string AsantiPinSet {
        get {
            return this.asantiPinSetField;
        }
        set {
            this.asantiPinSetField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string AsantiPinConfig {
        get {
            return this.asantiPinConfigField;
        }
        set {
            this.asantiPinConfigField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string AsantiCPM {
        get {
            return this.asantiCPMField;
        }
        set {
            this.asantiCPMField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public AsantiWhiteGenerationType AsantiWhiteGeneration {
        get {
            return this.asantiWhiteGenerationField;
        }
        set {
            this.asantiWhiteGenerationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool AsantiWhiteGenerationSpecified {
        get {
            return this.asantiWhiteGenerationFieldSpecified;
        }
        set {
            this.asantiWhiteGenerationFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public AsantiWhiteOrderType AsantiWhiteOrder {
        get {
            return this.asantiWhiteOrderField;
        }
        set {
            this.asantiWhiteOrderField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool AsantiWhiteOrderSpecified {
        get {
            return this.asantiWhiteOrderFieldSpecified;
        }
        set {
            this.asantiWhiteOrderFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Product {
        get {
            return this.productField;
        }
        set {
            this.productField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public PrintQualityType PrintQuality {
        get {
            return this.printQualityField;
        }
        set {
            this.printQualityField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool PrintQualitySpecified {
        get {
            return this.printQualityFieldSpecified;
        }
        set {
            this.printQualityFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string NamedFeatures {
        get {
            return this.namedFeaturesField;
        }
        set {
            this.namedFeaturesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool NoImpose {
        get {
            return this.noImposeField;
        }
        set {
            this.noImposeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool NoImposeSpecified {
        get {
            return this.noImposeFieldSpecified;
        }
        set {
            this.noImposeFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string TicketTemplate {
        get {
            return this.ticketTemplateField;
        }
        set {
            this.ticketTemplateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    //[System.ComponentModel.DefaultValueAttribute("")]
    public string Versions {
        get {
            return this.versionsField;
        }
        set {
            this.versionsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    //[System.ComponentModel.DefaultValueAttribute("")]
    public string VersionLayers {
        get {
            return this.versionLayersField;
        }
        set {
            this.versionLayersField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string AgentName {
        get {
            return this.agentNameField;
        }
        set {
            this.agentNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string AgentNameJDF {
        get {
            return this.agentNameJDFField;
        }
        set {
            this.agentNameJDFField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string AgentVersion {
        get {
            return this.agentVersionField;
        }
        set {
            this.agentVersionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string AgentVersionJDF {
        get {
            return this.agentVersionJDFField;
        }
        set {
            this.agentVersionJDFField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public ApoXMLDecimalSeparator DecimalSeparator {
        get {
            return this.decimalSeparatorField;
        }
        set {
            this.decimalSeparatorField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    //[System.ComponentModel.DefaultValueAttribute(ApoXMLThousandSeparator.Item)]
    public ApoXMLThousandSeparator ThousandSeparator {
        get {
            return this.thousandSeparatorField;
        }
        set {
            this.thousandSeparatorField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public ApoXMLUnit Unit {
        get {
            return this.unitField;
        }
        set {
            this.unitField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.agfa.com/apoxml")]
public partial class GeneralIDType {
    
    private string keyField;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Key {
        get {
            return this.keyField;
        }
        set {
            this.keyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.agfa.com/apoxml")]
public partial class PagesType {
    
    private string uRLField;
    
    private string pageCountField;
    
    private string pageIndexField;
    
    private decimal pageWidthField;
    
    private decimal pageHeightField;
    
    private string pageSizeField;
    
    private ISOPageSizeType pageSizeNameField;
    
    private bool pageSizeNameFieldSpecified;
    
    private string fileVersionField;
    
    public PagesType() {
        this.pageWidthField = ((decimal)(210m));
        this.pageHeightField = ((decimal)(297m));
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
    public string URL {
        get {
            return this.uRLField;
        }
        set {
            this.uRLField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string PageCount {
        get {
            return this.pageCountField;
        }
        set {
            this.pageCountField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string PageIndex {
        get {
            return this.pageIndexField;
        }
        set {
            this.pageIndexField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    //[System.ComponentModel.DefaultValueAttribute(typeof(decimal), "210")]
    public decimal PageWidth {
        get {
            return this.pageWidthField;
        }
        set {
            this.pageWidthField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    //[System.ComponentModel.DefaultValueAttribute(typeof(decimal), "297")]
    public decimal PageHeight {
        get {
            return this.pageHeightField;
        }
        set {
            this.pageHeightField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string PageSize {
        get {
            return this.pageSizeField;
        }
        set {
            this.pageSizeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public ISOPageSizeType PageSizeName {
        get {
            return this.pageSizeNameField;
        }
        set {
            this.pageSizeNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool PageSizeNameSpecified {
        get {
            return this.pageSizeNameFieldSpecified;
        }
        set {
            this.pageSizeNameFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string FileVersion {
        get {
            return this.fileVersionField;
        }
        set {
            this.fileVersionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.agfa.com/apoxml")]
public enum ISOPageSizeType {
    
    /// <remarks/>
    A1,
    
    /// <remarks/>
    A2,
    
    /// <remarks/>
    A3,
    
    /// <remarks/>
    A4,
    
    /// <remarks/>
    A5,
}

/// <remarks/>
[System.Xml.Serialization.XmlIncludeAttribute(typeof(BasePartType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(PartCoverType))]
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.agfa.com/apoxml")]
public partial class BaseBasePartType {
    
    private ColorType colorField;
    
    private PagesType pagesField;
    
    private PaperStockType paperStockField;
    
    private string partNameField;
    
    private string pressField;
    
    private ImposeWorkStyleType workStyleField;
    
    private string foldCatalogField;
    
    private decimal openWidthField;
    
    private bool openWidthFieldSpecified;
    
    private string commentsField;
    
    private string amountField;
    
    private bool independentPageNumberingField;
    
    private bool independentPageNumberingFieldSpecified;
    
    private string bindingOptionsField;
    
    private string pressSheetLayoutField;
    
    private string foldingSchemeSetField;
    
    private string autoFitRuleField;
    
    private string autoImposeRuleField;
    
    public BaseBasePartType() {
        this.workStyleField = ImposeWorkStyleType.Duplex;
        this.commentsField = "";
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public ColorType Color {
        get {
            return this.colorField;
        }
        set {
            this.colorField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public PagesType Pages {
        get {
            return this.pagesField;
        }
        set {
            this.pagesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public PaperStockType PaperStock {
        get {
            return this.paperStockField;
        }
        set {
            this.paperStockField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string PartName {
        get {
            return this.partNameField;
        }
        set {
            this.partNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Press {
        get {
            return this.pressField;
        }
        set {
            this.pressField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    //[System.ComponentModel.DefaultValueAttribute(ImposeWorkStyleType.Duplex)]
    public ImposeWorkStyleType WorkStyle {
        get {
            return this.workStyleField;
        }
        set {
            this.workStyleField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string FoldCatalog {
        get {
            return this.foldCatalogField;
        }
        set {
            this.foldCatalogField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal OpenWidth {
        get {
            return this.openWidthField;
        }
        set {
            this.openWidthField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool OpenWidthSpecified {
        get {
            return this.openWidthFieldSpecified;
        }
        set {
            this.openWidthFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    //[System.ComponentModel.DefaultValueAttribute("")]
    public string Comments {
        get {
            return this.commentsField;
        }
        set {
            this.commentsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string Amount {
        get {
            return this.amountField;
        }
        set {
            this.amountField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool IndependentPageNumbering {
        get {
            return this.independentPageNumberingField;
        }
        set {
            this.independentPageNumberingField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool IndependentPageNumberingSpecified {
        get {
            return this.independentPageNumberingFieldSpecified;
        }
        set {
            this.independentPageNumberingFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string BindingOptions {
        get {
            return this.bindingOptionsField;
        }
        set {
            this.bindingOptionsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string PressSheetLayout {
        get {
            return this.pressSheetLayoutField;
        }
        set {
            this.pressSheetLayoutField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string FoldingSchemeSet {
        get {
            return this.foldingSchemeSetField;
        }
        set {
            this.foldingSchemeSetField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string AutoFitRule {
        get {
            return this.autoFitRuleField;
        }
        set {
            this.autoFitRuleField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string AutoImposeRule {
        get {
            return this.autoImposeRuleField;
        }
        set {
            this.autoImposeRuleField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.agfa.com/apoxml")]
public partial class ColorType {
    
    private ColorTypeSpotColors[] spotColorsField;
    
    private ColorDetailsType frontField;
    
    private ColorDetailsType backField;
    
    private string nrColorsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("SpotColors", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public ColorTypeSpotColors[] SpotColors {
        get {
            return this.spotColorsField;
        }
        set {
            this.spotColorsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public ColorDetailsType Front {
        get {
            return this.frontField;
        }
        set {
            this.frontField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public ColorDetailsType Back {
        get {
            return this.backField;
        }
        set {
            this.backField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string NrColors {
        get {
            return this.nrColorsField;
        }
        set {
            this.nrColorsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.agfa.com/apoxml")]
public partial class ColorTypeSpotColors {
    
    private string spotNameField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string SpotName {
        get {
            return this.spotNameField;
        }
        set {
            this.spotNameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.agfa.com/apoxml")]
public partial class ColorDetailsType {
    
    private ColorDetailsTypeSpotColors[] spotColorsField;
    
    private string nrColorsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("SpotColors", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public ColorDetailsTypeSpotColors[] SpotColors {
        get {
            return this.spotColorsField;
        }
        set {
            this.spotColorsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string NrColors {
        get {
            return this.nrColorsField;
        }
        set {
            this.nrColorsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.agfa.com/apoxml")]
public partial class ColorDetailsTypeSpotColors {
    
    private string spotNameField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string SpotName {
        get {
            return this.spotNameField;
        }
        set {
            this.spotNameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.agfa.com/apoxml")]
public partial class PaperStockType {
    
    private GradeType gradeField;
    
    private bool gradeFieldSpecified;
    
    private ISOPaperSubstrateType iSOPaperSubstrateField;
    
    private bool iSOPaperSubstrateFieldSpecified;
    
    private string mediaTypeField;
    
    private string productIDField;
    
    private string coatingField;
    
    private string stockNameField;
    
    private string weightField;
    
    private decimal thicknessField;
    
    private bool thicknessFieldSpecified;
    
    private MediaUnitType mediaUnitField;
    
    private bool mediaUnitFieldSpecified;
    
    private decimal sheetWidthField;
    
    private bool sheetWidthFieldSpecified;
    
    private decimal sheetHeightField;
    
    private bool sheetHeightFieldSpecified;
    
    private string sheetSizeField;
    
    private string sheetSizeNameField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public GradeType Grade {
        get {
            return this.gradeField;
        }
        set {
            this.gradeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool GradeSpecified {
        get {
            return this.gradeFieldSpecified;
        }
        set {
            this.gradeFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public ISOPaperSubstrateType ISOPaperSubstrate {
        get {
            return this.iSOPaperSubstrateField;
        }
        set {
            this.iSOPaperSubstrateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ISOPaperSubstrateSpecified {
        get {
            return this.iSOPaperSubstrateFieldSpecified;
        }
        set {
            this.iSOPaperSubstrateFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string MediaType {
        get {
            return this.mediaTypeField;
        }
        set {
            this.mediaTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ProductID {
        get {
            return this.productIDField;
        }
        set {
            this.productIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Coating {
        get {
            return this.coatingField;
        }
        set {
            this.coatingField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string StockName {
        get {
            return this.stockNameField;
        }
        set {
            this.stockNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string Weight {
        get {
            return this.weightField;
        }
        set {
            this.weightField = value;
        }
    }


    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal Thickness
    {
        get
        {
            return this.thicknessField;
        }
        set
        {
            this.thicknessField = value;
        }
    }


    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ThicknessSpecified {
        get {
            return this.thicknessFieldSpecified;
        }
        set {
            this.thicknessFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public MediaUnitType MediaUnit {
        get {
            return this.mediaUnitField;
        }
        set {
            this.mediaUnitField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool MediaUnitSpecified {
        get {
            return this.mediaUnitFieldSpecified;
        }
        set {
            this.mediaUnitFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal SheetWidth {
        get {
            return this.sheetWidthField;
        }
        set {
            this.sheetWidthField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool SheetWidthSpecified {
        get {
            return this.sheetWidthFieldSpecified;
        }
        set {
            this.sheetWidthFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal SheetHeight {
        get {
            return this.sheetHeightField;
        }
        set {
            this.sheetHeightField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool SheetHeightSpecified {
        get {
            return this.sheetHeightFieldSpecified;
        }
        set {
            this.sheetHeightFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string SheetSize {
        get {
            return this.sheetSizeField;
        }
        set {
            this.sheetSizeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string SheetSizeName {
        get {
            return this.sheetSizeNameField;
        }
        set {
            this.sheetSizeNameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.agfa.com/apoxml")]
public enum GradeType {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("1")]
    Item1,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("2")]
    Item2,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("3")]
    Item3,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("4")]
    Item4,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("5")]
    Item5,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.agfa.com/apoxml")]
public enum ISOPaperSubstrateType {
    
    /// <remarks/>
    PS1,
    
    /// <remarks/>
    PS2,
    
    /// <remarks/>
    PS3,
    
    /// <remarks/>
    PS4,
    
    /// <remarks/>
    PS5,
    
    /// <remarks/>
    PS6,
    
    /// <remarks/>
    PS7,
    
    /// <remarks/>
    PS8,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.agfa.com/apoxml")]
public enum MediaUnitType {
    
    /// <remarks/>
    Roll,
    
    /// <remarks/>
    Sheet,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.agfa.com/apoxml")]
public enum ImposeWorkStyleType {
    
    /// <remarks/>
    Simplex,
    
    /// <remarks/>
    SingleSided,
    
    /// <remarks/>
    Duplex,
    
    /// <remarks/>
    WorkAndBack,
    
    /// <remarks/>
    SheetWise,
    
    /// <remarks/>
    WorkAndTumble,
    
    /// <remarks/>
    WorkAndTurn,
    
    /// <remarks/>
    Perfecting,
    
    /// <remarks/>
    Perfector,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.agfa.com/apoxml")]
public partial class BasePartType : BaseBasePartType {
    
    private PartTypeType partTypeField;
    
    public BasePartType() {
        this.partTypeField = PartTypeType.Plain;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    //[System.ComponentModel.DefaultValueAttribute(PartTypeType.Plain)]
    public PartTypeType PartType {
        get {
            return this.partTypeField;
        }
        set {
            this.partTypeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.agfa.com/apoxml")]
public enum PartTypeType {
    
    /// <remarks/>
    Cover,
    
    /// <remarks/>
    Body,
    
    /// <remarks/>
    Insert,
    
    /// <remarks/>
    Flatwork,
    
    /// <remarks/>
    Folded,
    
    /// <remarks/>
    Plain,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.agfa.com/apoxml")]
public partial class PartCoverType : BaseBasePartType {
    
    private CoverTypeType coverTypeField;
    
    private bool coverTypeFieldSpecified;
    
    private PartTypeType partTypeField;
    
    private bool partTypeFieldSpecified;
    
    public PartCoverType() {
        this.partTypeField = PartTypeType.Cover;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public CoverTypeType CoverType {
        get {
            return this.coverTypeField;
        }
        set {
            this.coverTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool CoverTypeSpecified {
        get {
            return this.coverTypeFieldSpecified;
        }
        set {
            this.coverTypeFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public PartTypeType PartType {
        get {
            return this.partTypeField;
        }
        set {
            this.partTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool PartTypeSpecified {
        get {
            return this.partTypeFieldSpecified;
        }
        set {
            this.partTypeFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.agfa.com/apoxml")]
public enum CoverTypeType {
    
    /// <remarks/>
    Spread,
    
    /// <remarks/>
    Standard,
    
    /// <remarks/>
    Spine,
    
    /// <remarks/>
    FrontFlap,
    
    /// <remarks/>
    BackFlap,
    
    /// <remarks/>
    FrontAndBackFlap,
    
    /// <remarks/>
    SpineAndFrontFlap,
    
    /// <remarks/>
    SpineAndBackFlap,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("SpineAndFrontFlap")]
    SpineAndFrontFlap1,
    
    /// <remarks/>
    SpineAndFrontAndBackFlap,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.agfa.com/apoxml")]
public partial class JMFType {
    
    private string eventURLField;
    
    private string resourceURLField;
    
    private ResourceClasses2SignalType resourceClasses2SignalField;
    
    private Notifications2SignalType notifications2SignalField;
    
    private bool notifications2SignalFieldSpecified;
    
    public JMFType() {
        this.resourceClasses2SignalField = ((ResourceClasses2SignalType.Consumable | ResourceClasses2SignalType.Handling) 
                    | ResourceClasses2SignalType.Parameter);
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
    public string EventURL {
        get {
            return this.eventURLField;
        }
        set {
            this.eventURLField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
    public string ResourceURL {
        get {
            return this.resourceURLField;
        }
        set {
            this.resourceURLField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    //[System.ComponentModel.DefaultValueAttribute(((ResourceClasses2SignalType.Consumable | ResourceClasses2SignalType.Handling) 
    //            | ResourceClasses2SignalType.Parameter))]
    public ResourceClasses2SignalType ResourceClasses2Signal {
        get {
            return this.resourceClasses2SignalField;
        }
        set {
            this.resourceClasses2SignalField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public Notifications2SignalType Notifications2Signal {
        get {
            return this.notifications2SignalField;
        }
        set {
            this.notifications2SignalField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool Notifications2SignalSpecified {
        get {
            return this.notifications2SignalFieldSpecified;
        }
        set {
            this.notifications2SignalFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.FlagsAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.agfa.com/apoxml")]
public enum ResourceClasses2SignalType {
    
    /// <remarks/>
    Consumable = 1,
    
    /// <remarks/>
    Handling = 2,
    
    /// <remarks/>
    Parameter = 4,
}

/// <remarks/>
[System.FlagsAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.agfa.com/apoxml")]
public enum Notifications2SignalType {
    
    /// <remarks/>
    Information = 1,
    
    /// <remarks/>
    Warning = 2,
    
    /// <remarks/>
    Error = 4,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.agfa.com/apoxml")]
public partial class BindingType {
    
    private MethodType methodField;
    
    private bool methodFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public MethodType Method {
        get {
            return this.methodField;
        }
        set {
            this.methodField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool MethodSpecified {
        get {
            return this.methodFieldSpecified;
        }
        set {
            this.methodFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.agfa.com/apoxml")]
public enum MethodType {
    
    /// <remarks/>
    Nested,
    
    /// <remarks/>
    Stacked,
    
    /// <remarks/>
    Unbound,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.agfa.com/apoxml")]
public partial class CSRType {
    
    private string firstNameField;
    
    private string lastNameField;
    
    private string phoneField;
    
    private string emailField;
    
    private string jDFProductIDField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string FirstName {
        get {
            return this.firstNameField;
        }
        set {
            this.firstNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string LastName {
        get {
            return this.lastNameField;
        }
        set {
            this.lastNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Phone {
        get {
            return this.phoneField;
        }
        set {
            this.phoneField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Email {
        get {
            return this.emailField;
        }
        set {
            this.emailField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string JDFProductID {
        get {
            return this.jDFProductIDField;
        }
        set {
            this.jDFProductIDField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.agfa.com/apoxml")]
public partial class MultiContactType {
    
    private BaseCompanyType companyField;
    
    private BasePersonType personField;
    
    private RolesType rolesField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public BaseCompanyType Company {
        get {
            return this.companyField;
        }
        set {
            this.companyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public BasePersonType Person {
        get {
            return this.personField;
        }
        set {
            this.personField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public RolesType Roles {
        get {
            return this.rolesField;
        }
        set {
            this.rolesField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.agfa.com/apoxml")]
public partial class BaseCompanyType {
    
    private string companyField;
    
    private string phoneField;
    
    private string streetField;
    
    private string zIPField;
    
    private string stateProvinceField;
    
    private string cityField;
    
    private string countryField;
    
    private string jDFProductIDField;
    
    private string printCenterField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Company {
        get {
            return this.companyField;
        }
        set {
            this.companyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Phone {
        get {
            return this.phoneField;
        }
        set {
            this.phoneField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Street {
        get {
            return this.streetField;
        }
        set {
            this.streetField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ZIP {
        get {
            return this.zIPField;
        }
        set {
            this.zIPField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string StateProvince {
        get {
            return this.stateProvinceField;
        }
        set {
            this.stateProvinceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string City {
        get {
            return this.cityField;
        }
        set {
            this.cityField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Country {
        get {
            return this.countryField;
        }
        set {
            this.countryField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string JDFProductID {
        get {
            return this.jDFProductIDField;
        }
        set {
            this.jDFProductIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string PrintCenter {
        get {
            return this.printCenterField;
        }
        set {
            this.printCenterField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.agfa.com/apoxml")]
public partial class BasePersonType {
    
    private string prefixField;
    
    private string titleField;
    
    private string firstNameField;
    
    private string lastNameField;
    
    private string fixPhoneField;
    
    private string mobilePhoneField;
    
    private string emailField;
    
    private string jDFProductIDField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Prefix {
        get {
            return this.prefixField;
        }
        set {
            this.prefixField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Title {
        get {
            return this.titleField;
        }
        set {
            this.titleField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string FirstName {
        get {
            return this.firstNameField;
        }
        set {
            this.firstNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string LastName {
        get {
            return this.lastNameField;
        }
        set {
            this.lastNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string FixPhone {
        get {
            return this.fixPhoneField;
        }
        set {
            this.fixPhoneField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string MobilePhone {
        get {
            return this.mobilePhoneField;
        }
        set {
            this.mobilePhoneField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Email {
        get {
            return this.emailField;
        }
        set {
            this.emailField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string JDFProductID {
        get {
            return this.jDFProductIDField;
        }
        set {
            this.jDFProductIDField = value;
        }
    }
}

/// <remarks/>
[System.FlagsAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.agfa.com/apoxml")]
public enum RolesType {
    
    /// <remarks/>
    Administrator = 1,
    
    /// <remarks/>
    Approver = 2,
    
    /// <remarks/>
    Customer = 4,
    
    /// <remarks/>
    Sender = 8,
    
    /// <remarks/>
    Guest = 16,
    
    /// <remarks/>
    AdminContact = 32,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.agfa.com/apoxml")]
public partial class BaseContactType {
    
    private BaseCompanyType companyField;
    
    private BasePersonType personField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public BaseCompanyType Company {
        get {
            return this.companyField;
        }
        set {
            this.companyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public BasePersonType Person {
        get {
            return this.personField;
        }
        set {
            this.personField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.agfa.com/apoxml")]
public enum PrintProcessType {
    
    /// <remarks/>
    ConventionalPrinting,
    
    /// <remarks/>
    DigitalPrinting,
    
    /// <remarks/>
    WideFormatPrinting,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.agfa.com/apoxml")]
public enum PublishLevelType {
    
    /// <remarks/>
    DontPublish,
    
    /// <remarks/>
    Publish,
    
    /// <remarks/>
    PublishForApproval,
    
    /// <remarks/>
    PublishForUpload,
    
    /// <remarks/>
    PublishInternally,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.agfa.com/apoxml")]
public enum AsantiWhiteGenerationType {
    
    /// <remarks/>
    FillEntireImagePrinter,
    
    /// <remarks/>
    FillEntireImageRender,
    
    /// <remarks/>
    FromImage,
    
    /// <remarks/>
    InverseSolidImageMaskRender,
    
    /// <remarks/>
    InverseVariableImageMaskRender,
    
    /// <remarks/>
    None,
    
    /// <remarks/>
    PixelMaskPrinter,
    
    /// <remarks/>
    SolidImageMaskPixelBasedRender,
    
    /// <remarks/>
    SolidImageMaskRender,
    
    /// <remarks/>
    VariableImageMaskRender,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.agfa.com/apoxml")]
public enum AsantiWhiteOrderType {
    
    /// <remarks/>
    PostWhite,
    
    /// <remarks/>
    PreWhite,
    
    /// <remarks/>
    PreWhite_OnMedia,
    
    /// <remarks/>
    SandwichWhite,
    
    /// <remarks/>
    SandwichWhite_OnWhite,
    
    /// <remarks/>
    SpotWhite,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.agfa.com/apoxml")]
public enum PrintQualityType {
    
    /// <remarks/>
    Balanced,
    
    /// <remarks/>
    CostEffective,
    
    /// <remarks/>
    Fastest,
    
    /// <remarks/>
    HighestQuality,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.agfa.com/apoxml")]
public enum ApoXMLDecimalSeparator {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute(",")]
    Item,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute(".")]
    Item1,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.agfa.com/apoxml")]
public enum ApoXMLThousandSeparator {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute(".")]
    Item,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute(",")]
    Item1,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("\"")]
    Item2,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.agfa.com/apoxml")]
public enum ApoXMLUnit {
    
    /// <remarks/>
    mm,
    
    /// <remarks/>
    inch,
    
    /// <remarks/>
    pts,
}

}
