namespace Asanti {

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.agfa.com/apoxml")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.agfa.com/apoxml", IsNullable=false)]
public partial class ApoXML : ApoXmlCsLib.ApoXmlBase<Asanti.ApoXML>
    {
    
    private GeneralIDType[] generalIDsField;
    
    private BaseContactType customerContactField;
    
    private PaperStockType paperStockField;
    
    private BasePartType[] partField;
    
    private string commentsField;
    
    private string endDateField;
    
    private string jobNameField;
    
    private string orderNumberField;
    
    private string priorityField;
    
    private PrintProcessType printProcessField;
    
    private string asantiQualityField;
    
    private string asantiImagePresetField;
    
    private string asantiPinSetField;
    
    private string asantiPinConfigField;
    
    private string asantiCPMField;
    
    private AsantiWhiteGenerationType asantiWhiteGenerationField;
    
    private bool asantiWhiteGenerationFieldSpecified;
    
    private AsantiWhiteOrderType asantiWhiteOrderField;
    
    private bool asantiWhiteOrderFieldSpecified;
    
    private PrintQualityType printQualityField;
    
    private string ticketTemplateField;
    
    private string agentNameField;
    
    private string agentNameJDFField;
    
    private string agentVersionField;
    
    private string agentVersionJDFField;
    
    private ApoXMLDecimalSeparator decimalSeparatorField;
    
    private ApoXMLThousandSeparator thousandSeparatorField;
    
    private ApoXMLUnit unitField;
    
    public ApoXML() {
        this.printProcessField = PrintProcessType.WideFormatPrinting;
        this.printQualityField = PrintQualityType.CostEffective;
        this.decimalSeparatorField = ApoXMLDecimalSeparator.Item;
        this.thousandSeparatorField = ApoXMLThousandSeparator.Item;
        this.unitField = ApoXMLUnit.mm;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlArrayItemAttribute("GeneralID", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
    public GeneralIDType[] GeneralIDs {
        get {
            return this.generalIDsField;
        }
        set {
            this.generalIDsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public BaseContactType CustomerContact {
        get {
            return this.customerContactField;
        }
        set {
            this.customerContactField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public PaperStockType PaperStock {
        get {
            return this.paperStockField;
        }
        set {
            this.paperStockField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Part", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public BasePartType[] Part {
        get {
            return this.partField;
        }
        set {
            this.partField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Comments {
        get {
            return this.commentsField;
        }
        set {
            this.commentsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string EndDate {
        get {
            return this.endDateField;
        }
        set {
            this.endDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string JobName {
        get {
            return this.jobNameField;
        }
        set {
            this.jobNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string OrderNumber {
        get {
            return this.orderNumberField;
        }
        set {
            this.orderNumberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string Priority {
        get {
            return this.priorityField;
        }
        set {
            this.priorityField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public PrintProcessType PrintProcess {
        get {
            return this.printProcessField;
        }
        set {
            this.printProcessField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string AsantiQuality {
        get {
            return this.asantiQualityField;
        }
        set {
            this.asantiQualityField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string AsantiImagePreset {
        get {
            return this.asantiImagePresetField;
        }
        set {
            this.asantiImagePresetField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string AsantiPinSet {
        get {
            return this.asantiPinSetField;
        }
        set {
            this.asantiPinSetField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string AsantiPinConfig {
        get {
            return this.asantiPinConfigField;
        }
        set {
            this.asantiPinConfigField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string AsantiCPM {
        get {
            return this.asantiCPMField;
        }
        set {
            this.asantiCPMField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public AsantiWhiteGenerationType AsantiWhiteGeneration {
        get {
            return this.asantiWhiteGenerationField;
        }
        set {
            this.asantiWhiteGenerationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool AsantiWhiteGenerationSpecified {
        get {
            return this.asantiWhiteGenerationFieldSpecified;
        }
        set {
            this.asantiWhiteGenerationFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public AsantiWhiteOrderType AsantiWhiteOrder {
        get {
            return this.asantiWhiteOrderField;
        }
        set {
            this.asantiWhiteOrderField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool AsantiWhiteOrderSpecified {
        get {
            return this.asantiWhiteOrderFieldSpecified;
        }
        set {
            this.asantiWhiteOrderFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    //[System.ComponentModel.DefaultValueAttribute(PrintQualityType.CostEffective)]
    public PrintQualityType PrintQuality {
        get {
            return this.printQualityField;
        }
        set {
            this.printQualityField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string TicketTemplate {
        get {
            return this.ticketTemplateField;
        }
        set {
            this.ticketTemplateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string AgentName {
        get {
            return this.agentNameField;
        }
        set {
            this.agentNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string AgentNameJDF {
        get {
            return this.agentNameJDFField;
        }
        set {
            this.agentNameJDFField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string AgentVersion {
        get {
            return this.agentVersionField;
        }
        set {
            this.agentVersionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string AgentVersionJDF {
        get {
            return this.agentVersionJDFField;
        }
        set {
            this.agentVersionJDFField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    //[System.ComponentModel.DefaultValueAttribute(ApoXMLDecimalSeparator.Item)]
    public ApoXMLDecimalSeparator DecimalSeparator {
        get {
            return this.decimalSeparatorField;
        }
        set {
            this.decimalSeparatorField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    //[System.ComponentModel.DefaultValueAttribute(ApoXMLThousandSeparator.Item)]
    public ApoXMLThousandSeparator ThousandSeparator {
        get {
            return this.thousandSeparatorField;
        }
        set {
            this.thousandSeparatorField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    //[System.ComponentModel.DefaultValueAttribute(ApoXMLUnit.mm)]
    public ApoXMLUnit Unit {
        get {
            return this.unitField;
        }
        set {
            this.unitField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.agfa.com/apoxml")]
public partial class GeneralIDType {
    
    private string keyField;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Key {
        get {
            return this.keyField;
        }
        set {
            this.keyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.agfa.com/apoxml")]
public partial class PagesType {
    
    private string uRLField;
    
    private string pageCountField;
    
    private string pageIndexField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
    public string URL {
        get {
            return this.uRLField;
        }
        set {
            this.uRLField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string PageCount {
        get {
            return this.pageCountField;
        }
        set {
            this.pageCountField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string PageIndex {
        get {
            return this.pageIndexField;
        }
        set {
            this.pageIndexField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.agfa.com/apoxml")]
public partial class BasePartType {
    
    private PagesType pagesField;
    
    private PaperStockType paperStockField;
    
    private string amountField;
    
    private string commentsField;
    
    private string partNameField;
    
    private string pressField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public PagesType Pages {
        get {
            return this.pagesField;
        }
        set {
            this.pagesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public PaperStockType PaperStock {
        get {
            return this.paperStockField;
        }
        set {
            this.paperStockField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string Amount {
        get {
            return this.amountField;
        }
        set {
            this.amountField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Comments {
        get {
            return this.commentsField;
        }
        set {
            this.commentsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string PartName {
        get {
            return this.partNameField;
        }
        set {
            this.partNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Press {
        get {
            return this.pressField;
        }
        set {
            this.pressField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.agfa.com/apoxml")]
public partial class PaperStockType {
    
    private string mediaTypeField;
    
    private string productIDField;
    
    private string stockNameField;
    
    private decimal thicknessField;
    
    private bool thicknessFieldSpecified;
    
    private MediaUnitType mediaUnitField;
    
    private bool mediaUnitFieldSpecified;
    
    private decimal sheetWidthField;
    
    private bool sheetWidthFieldSpecified;
    
    private decimal sheetHeightField;
    
    private bool sheetHeightFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string MediaType {
        get {
            return this.mediaTypeField;
        }
        set {
            this.mediaTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ProductID {
        get {
            return this.productIDField;
        }
        set {
            this.productIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string StockName {
        get {
            return this.stockNameField;
        }
        set {
            this.stockNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal Thickness {
        get {
            return this.thicknessField;
        }
        set {
            this.thicknessField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ThicknessSpecified {
        get {
            return this.thicknessFieldSpecified;
        }
        set {
            this.thicknessFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public MediaUnitType MediaUnit {
        get {
            return this.mediaUnitField;
        }
        set {
            this.mediaUnitField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool MediaUnitSpecified {
        get {
            return this.mediaUnitFieldSpecified;
        }
        set {
            this.mediaUnitFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal SheetWidth {
        get {
            return this.sheetWidthField;
        }
        set {
            this.sheetWidthField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool SheetWidthSpecified {
        get {
            return this.sheetWidthFieldSpecified;
        }
        set {
            this.sheetWidthFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal SheetHeight {
        get {
            return this.sheetHeightField;
        }
        set {
            this.sheetHeightField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool SheetHeightSpecified {
        get {
            return this.sheetHeightFieldSpecified;
        }
        set {
            this.sheetHeightFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.agfa.com/apoxml")]
public enum MediaUnitType {
    
    /// <remarks/>
    Roll,
    
    /// <remarks/>
    Sheet,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.agfa.com/apoxml")]
public partial class BasePersonType {
    
    private string titleField;
    
    private string firstNameField;
    
    private string lastNameField;
    
    private string fixPhoneField;
    
    private string emailField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Title {
        get {
            return this.titleField;
        }
        set {
            this.titleField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string FirstName {
        get {
            return this.firstNameField;
        }
        set {
            this.firstNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string LastName {
        get {
            return this.lastNameField;
        }
        set {
            this.lastNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string FixPhone {
        get {
            return this.fixPhoneField;
        }
        set {
            this.fixPhoneField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Email {
        get {
            return this.emailField;
        }
        set {
            this.emailField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.agfa.com/apoxml")]
public partial class BaseCompanyType {
    
    private string companyField;
    
    private string phoneField;
    
    private string streetField;
    
    private string zIPField;
    
    private string stateProvinceField;
    
    private string cityField;
    
    private string countryField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Company {
        get {
            return this.companyField;
        }
        set {
            this.companyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Phone {
        get {
            return this.phoneField;
        }
        set {
            this.phoneField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Street {
        get {
            return this.streetField;
        }
        set {
            this.streetField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ZIP {
        get {
            return this.zIPField;
        }
        set {
            this.zIPField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string StateProvince {
        get {
            return this.stateProvinceField;
        }
        set {
            this.stateProvinceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string City {
        get {
            return this.cityField;
        }
        set {
            this.cityField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Country {
        get {
            return this.countryField;
        }
        set {
            this.countryField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.agfa.com/apoxml")]
public partial class BaseContactType {
    
    private BaseCompanyType companyField;
    
    private BasePersonType personField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public BaseCompanyType Company {
        get {
            return this.companyField;
        }
        set {
            this.companyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public BasePersonType Person {
        get {
            return this.personField;
        }
        set {
            this.personField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.agfa.com/apoxml")]
public enum PrintProcessType {
    
    /// <remarks/>
    WideFormatPrinting,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.agfa.com/apoxml")]
public enum AsantiWhiteGenerationType {
    
    /// <remarks/>
    FillEntireImagePrinter,
    
    /// <remarks/>
    FillEntireImageRender,
    
    /// <remarks/>
    FromImage,
    
    /// <remarks/>
    InverseSolidImageMaskRender,
    
    /// <remarks/>
    InverseVariableImageMaskRender,
    
    /// <remarks/>
    None,
    
    /// <remarks/>
    PixelMaskPrinter,
    
    /// <remarks/>
    SolidImageMaskPixelBasedRender,
    
    /// <remarks/>
    SolidImageMaskRender,
    
    /// <remarks/>
    VariableImageMaskRender,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.agfa.com/apoxml")]
public enum AsantiWhiteOrderType {
    
    /// <remarks/>
    PostWhite,
    
    /// <remarks/>
    PreWhite,
    
    /// <remarks/>
    PreWhite_OnMedia,
    
    /// <remarks/>
    SandwichWhite,
    
    /// <remarks/>
    SandwichWhite_OnWhite,
    
    /// <remarks/>
    SpotWhite,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.agfa.com/apoxml")]
public enum PrintQualityType {
    
    /// <remarks/>
    Balanced,
    
    /// <remarks/>
    CostEffective,
    
    /// <remarks/>
    Fastest,
    
    /// <remarks/>
    HighestQuality,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.agfa.com/apoxml")]
public enum ApoXMLDecimalSeparator {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute(",")]
    Item,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute(".")]
    Item1,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.agfa.com/apoxml")]
public enum ApoXMLThousandSeparator {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute(".")]
    Item,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute(",")]
    Item1,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("\"")]
    Item2,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.agfa.com/apoxml")]
public enum ApoXMLUnit {
    
    /// <remarks/>
    mm,
    
    /// <remarks/>
    inch,
    
    /// <remarks/>
    pts,
}

}